services:
  nfc.mvp:
    container_name: nfcDb
    hostname: nfcDb
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "SqlServer2019!"
      ACCEPT_EULA: "Y"
    networks:
      - service_nfc_network
    restart: always

  nfc.redis:
    container_name: nfc_redis_db
    image: redis:latest
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    networks:
      - service_nfc_network
    restart: always

  localstack:
    image: localstack/localstack:latest
    restart: unless-stopped
    ports:  
      - 4566:4566
      - 4571:4571
    environment:
      - SERVICES=sns,sqs,s3
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - EXTRA_CORS_ALLOWED_ORIGINS=https://app.localstack.cloud.
    volumes:
      - ./data:/var/lib/localstack      
      - /var/run/docker.sock:/var/run/docker.sock
      - ./bin:/docker-entrypoint-initaws.d

  aws-cli:
    image: amazon/aws-cli:latest
    depends_on:
      - localstack
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./setup.sh:/tmp/setup.sh
    entrypoint: /bin/bash
    command: 
      - -c
      - |
        tr -d '\r' < /tmp/setup.sh > /tmp/setup_unix.sh && \
        chmod +x /tmp/setup_unix.sh && \
        /tmp/setup_unix.sh

volumes:
  redis-data:

networks:
  service_nfc_network:
    driver: bridge
