<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="13.1.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.0" />
    <PackageReference Include="StackExchange.Redis" Version="2.8.31" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nfc.Application\Nfc.Application.csproj" />
    <ProjectReference Include="..\Nfc.Infra.CrossCutting.Commons\Nfc.Infra.CrossCutting.Commons.csproj" />
    <ProjectReference Include="..\Nfc.Infra.Data.EF\Nfc.Infra.Data.EF.csproj" />
    <ProjectReference Include="..\Nfc.Infra.Data.Redis\Nfc.Infra.Data.Redis.csproj" />
    <ProjectReference Include="..\Nfc.Infra.HangFire\Nfc.Infra.HangFire.csproj" />
    <ProjectReference Include="..\Nfc.Infra.Storage\Nfc.Infra.Storage.csproj" />
  </ItemGroup>

</Project>
